#!/bin/bash
# Arkeo Sentinel One-Click Installer
# Generated by the Arkeo Marketplace wizard
# Usage: curl -sL <url> | ENV_VARS bash
#
# This script:
# 1. Installs Docker (if not present)
# 2. Configures sentinel as a systemd service
# 3. Sets up nginx + free SSL (if domain provided)
# 4. Starts the sentinel
# 5. Verifies everything works

set -euo pipefail

# ── Configuration (passed as env vars by wizard) ──────────────
PROVIDER_PUBKEY="${PROVIDER_PUBKEY:?ERROR: PROVIDER_PUBKEY is required}"
SOURCE_CHAIN="${SOURCE_CHAIN:-arkeo-main-v1}"
HUB_URI="${HUB_URI:-https://rest-seed.arkeo.network}"
SERVICE_NAME="${SERVICE_NAME:-arkeo-mainnet-fullnode}"
RPC_URL="${RPC_URL:-http://localhost:26657}"
FREE_RATE_LIMIT="${FREE_RATE_LIMIT:-10}"
CONTRACT_RATE_LIMIT="${CONTRACT_RATE_LIMIT:-100}"
MONIKER="${MONIKER:-My Arkeo Provider}"
DESCRIPTION="${DESCRIPTION:-}"
LOCATION="${LOCATION:-}"
DOMAIN="${DOMAIN:-}"
EVENT_STREAM="${EVENT_STREAM:-127.0.0.1:26657}"
PROVIDER_HUB="${PROVIDER_HUB:-http://127.0.0.1:1317}"
PORT="${PORT:-3636}"

# Strip protocol from domain if accidentally included
DOMAIN="${DOMAIN#https://}"
DOMAIN="${DOMAIN#http://}"
DOMAIN="${DOMAIN%/}"
# ──────────────────────────────────────────────────────────────

CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'
BOLD='\033[1m'

echo ""
echo -e "${CYAN}${BOLD}╔══════════════════════════════════════════╗${NC}"
echo -e "${CYAN}${BOLD}║     🛡️  Arkeo Sentinel Installer         ║${NC}"
echo -e "${CYAN}${BOLD}╚══════════════════════════════════════════╝${NC}"
echo ""
echo -e "  Provider:  ${BOLD}${MONIKER}${NC}"
echo -e "  Service:   ${SERVICE_NAME}"
echo -e "  Node RPC:  ${RPC_URL}"
if [ -n "$DOMAIN" ]; then
echo -e "  Domain:    ${DOMAIN}"
fi
echo ""

# ── Step 1: Install sentinel binary ──────────────────────────
echo -e "${CYAN}[1/5]${NC} Installing sentinel..."

if [ -f /usr/local/bin/sentinel ]; then
    echo -e "  ${GREEN}✓${NC} Sentinel binary already installed"
elif [ -f /root/go/bin/sentinel ]; then
    ln -sf /root/go/bin/sentinel /usr/local/bin/sentinel
    echo -e "  ${GREEN}✓${NC} Sentinel binary found and linked"
else
    # Download pre-built binary
    echo -e "  ${YELLOW}→${NC} Downloading sentinel binary..."
    if command -v go &>/dev/null; then
        go install github.com/arkeonetwork/arkeo/sentinel@latest 2>/dev/null && \
            ln -sf ~/go/bin/sentinel /usr/local/bin/sentinel && \
            echo -e "  ${GREEN}✓${NC} Sentinel installed via Go" || \
            echo -e "  ${RED}✗${NC} Failed to install. Please install Go 1.22+ and retry."
    else
        echo -e "  ${RED}✗${NC} Go not found. Install Go 1.22+ first: https://go.dev/dl/"
        echo -e "  Then run: go install github.com/arkeonetwork/arkeo/sentinel@latest"
        exit 1
    fi
fi

# ── Step 2: Configure sentinel systemd service ───────────────
echo -e "${CYAN}[2/5]${NC} Configuring sentinel service..."

# Create required directories
mkdir -p /root/.arkeo/claims /root/.arkeo/contract_configs /root/.arkeo/provider_configs

# Write minimal YAML config (sentinel reads most from env vars)
cat > /root/.arkeo/config.yaml << EOF
provider:
  pubkey: "${PROVIDER_PUBKEY}"
  name: "${MONIKER}"

services:
  - name: ${SERVICE_NAME}
    id: 2
    type: rpc
    rpc_url: ${RPC_URL}

api:
  listen_addr: "0.0.0.0:${PORT}"
EOF

# Create systemd service
cat > /etc/systemd/system/sentinel.service << EOF
[Unit]
Description=Arkeo Sentinel (Provider)
After=network-online.target

[Service]
User=root
WorkingDirectory=/root
ExecStart=/usr/local/bin/sentinel --config /root/.arkeo/config.yaml
Restart=on-failure
RestartSec=5
LimitNOFILE=65535
Environment="MONIKER=${MONIKER}"
Environment="WEBSITE="
Environment="DESCRIPTION=${DESCRIPTION}"
Environment="LOCATION=${LOCATION}"
Environment="EVENT_STREAM_HOST=${EVENT_STREAM}"
Environment="PROVIDER_HUB_URI=${PROVIDER_HUB}"
Environment="SOURCE_CHAIN=arkeo"
Environment="CLAIM_STORE_LOCATION=/root/.arkeo/claims"
Environment="CONTRACT_CONFIG_STORE_LOCATION=/root/.arkeo/contract_configs"
Environment="PROVIDER_CONFIG_STORE_LOCATION=/root/.arkeo/provider_configs"
Environment="FREE_RATE_LIMIT=${FREE_RATE_LIMIT}"
Environment="LOG_LEVEL=info"
Environment="PORT=${PORT}"
Environment="PROVIDER_PUBKEY=${PROVIDER_PUBKEY}"

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
echo -e "  ${GREEN}✓${NC} Sentinel service configured"

# ── Step 3: Set up HTTPS (if domain provided) ────────────────
if [ -n "$DOMAIN" ]; then
    echo -e "${CYAN}[3/5]${NC} Setting up HTTPS for ${DOMAIN}..."
    
    # Install nginx and certbot if needed
    if ! command -v nginx &>/dev/null; then
        apt-get update -qq && apt-get install -y -qq nginx certbot python3-certbot-nginx > /dev/null 2>&1
        echo -e "  ${GREEN}✓${NC} Nginx + Certbot installed"
    else
        if ! command -v certbot &>/dev/null; then
            apt-get update -qq && apt-get install -y -qq certbot python3-certbot-nginx > /dev/null 2>&1
        fi
        echo -e "  ${GREEN}✓${NC} Nginx already installed"
    fi
    
    # Write nginx config
    cat > /etc/nginx/sites-available/arkeo-sentinel << NGINXEOF
server {
    server_name ${DOMAIN};
    
    location / {
        proxy_pass http://127.0.0.1:${PORT}/;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        
        # Prevent duplicate CORS headers
        proxy_hide_header Access-Control-Allow-Origin;
        proxy_hide_header Access-Control-Allow-Methods;
        proxy_hide_header Access-Control-Allow-Headers;
        
        add_header Access-Control-Allow-Origin '*' always;
        add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS' always;
        add_header Access-Control-Allow-Headers 'Content-Type, Authorization, X-Arkauth' always;
        if (\$request_method = OPTIONS) { return 204; }
    }
    
    listen 80;
}
NGINXEOF
    
    ln -sf /etc/nginx/sites-available/arkeo-sentinel /etc/nginx/sites-enabled/
    rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true
    nginx -t > /dev/null 2>&1 && systemctl reload nginx
    
    # Get SSL cert
    echo -e "  ${YELLOW}→${NC} Getting SSL certificate (this may take a minute)..."
    certbot --nginx -d "${DOMAIN}" --non-interactive --agree-tos --register-unsafely-without-email --redirect > /dev/null 2>&1 && \
        echo -e "  ${GREEN}✓${NC} HTTPS configured with auto-renewal" || \
        echo -e "  ${YELLOW}⚠${NC} SSL setup failed. Run 'certbot --nginx -d ${DOMAIN}' manually."
else
    echo -e "${CYAN}[3/5]${NC} Skipping HTTPS (no domain provided)"
    echo -e "  ${YELLOW}ℹ${NC} Sentinel will be available at http://$(curl -s ifconfig.me 2>/dev/null || echo 'YOUR_IP'):${PORT}"
fi

# ── Step 4: Start sentinel ────────────────────────────────────
echo -e "${CYAN}[4/5]${NC} Starting sentinel..."

systemctl enable sentinel > /dev/null 2>&1
systemctl start sentinel

# Wait for startup
sleep 4

if systemctl is-active --quiet sentinel; then
    echo -e "  ${GREEN}✓${NC} Sentinel is running"
else
    echo -e "  ${RED}✗${NC} Sentinel failed to start. Check: journalctl -u sentinel -n 20"
    exit 1
fi

# ── Step 5: Verify ────────────────────────────────────────────
echo -e "${CYAN}[5/5]${NC} Verifying..."

# Test local
HEALTH=$(curl -s --max-time 5 "http://localhost:${PORT}/metadata.json" 2>/dev/null)
if echo "$HEALTH" | grep -q "moniker"; then
    echo -e "  ${GREEN}✓${NC} Sentinel responding locally"
else
    echo -e "  ${YELLOW}⚠${NC} Sentinel not responding yet — may need a few more seconds"
fi

# Test public (if domain)
if [ -n "$DOMAIN" ]; then
    sleep 2
    PUBLIC=$(curl -s --max-time 10 "https://${DOMAIN}/metadata.json" 2>/dev/null)
    if echo "$PUBLIC" | grep -q "moniker"; then
        echo -e "  ${GREEN}✓${NC} Public HTTPS endpoint working"
    else
        echo -e "  ${YELLOW}⚠${NC} Public endpoint not responding — DNS may need a few minutes"
    fi
fi

# ── Done ──────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}╔══════════════════════════════════════════╗${NC}"
echo -e "${GREEN}${BOLD}║     🚀  Sentinel is Live!                ║${NC}"
echo -e "${GREEN}${BOLD}╚══════════════════════════════════════════╝${NC}"
echo ""
if [ -n "$DOMAIN" ]; then
echo -e "  Your sentinel: ${BOLD}https://${DOMAIN}${NC}"
else
echo -e "  Your sentinel: ${BOLD}http://$(curl -s ifconfig.me 2>/dev/null || echo 'YOUR_IP'):${PORT}${NC}"
fi
echo -e "  Config:        /root/.arkeo/config.yaml"
echo -e "  Logs:          journalctl -u sentinel -f"
echo -e "  Restart:       systemctl restart sentinel"
echo ""
echo -e "  ${CYAN}Go back to the marketplace wizard and click 'Test My Sentinel'${NC}"
echo ""
